[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "pytest>=9.0.0,<10",
    "pytest-mock>=3,<4",
    "pytest-cov>=7.0.0,<8",
    "pytest-xdist>=3,<4",
    "coverage>=7.6.4,<8",
    "ruff>=0.11.5,<1",
]
