[project]
name = "wps-wf1"
version = "0.1.0"
description = "Wildfire Predictive Services Unit WF1 utils"
authors = [
    { name = "Darren Boss", email = "darren.boss@gov.bc.ca" }
]
requires-python = ">=3.12.3,<4.0"
dependencies = [
    "aiohttp>=3.13.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/wps_wf1"]
