[project]
name = "wps-api"
version = "0.1.0"
description = "Wildfire Predictive Services Unit API"
authors = [{ name = "Sybrand Strauss", email = "sybrand.strauss@gov.bc.ca" }]
requires-python = ">=3.12.3,<4.0"
dependencies = [
    "wps-shared",
    "wps-sfms",
    "fastapi>=0,<1",
    "requests>=2,<3",
    "aiodns>=4,<5",
    "aiohttp>=3,<4",
    "pandas>=2,<3",
    "pyjwt>=2,<3",
    "cryptography>=46.0.0,<47",
    "sqlalchemy>=2,<3",
    "psycopg2>=2,<3",
    "postgres>=4,<5",
    "python-decouple>=3,<4",
    "uvicorn>=0,<1",
    "alembic>=1,<2",
    "requests-ntlm>=1,<2",
    "scipy>=1,<2",
    "geoalchemy2>=0,<1",
    "aiofiles>=25.0.0,<26",
    "jinja2>=3,<4",
    "numpy==2.3.*",
    "aiobotocore==2.15.1",
    "rpy2>=3.4.5,<4",
    "redis>=7.0.0,<8",
    "pyjnius>=1.3.0,<2",
    "hiredis>=3.0.0,<4",
    "pdfkit>=1.0.0,<2",
    "asyncpg>=0.30.0,<1",
    "python-multipart>=0.0.18,<1",
    "gunicorn>=23.0.0,<24",
    "setuptools>=80.0.0,<81",
    "nats-py>=2.1.7,<3",
    "affine>=2.3.1,<3",
    "scikit-learn>=1.1.3,<2",
    "httpx>=0.27.0,<1",
    "orjson>=3.9.0,<4",
    "greenlet>=3.0.0,<4",
    "sentry-sdk[fastapi]>=2.0.1,<3",
    "numba==0.63.*",
    "cffdrs",
    "geopandas>=1.0.1,<2",
    "shapely>=2.0.5,<3",
    "gdal==3.12.1",
    "wps-wf1",
]

[project.optional-dependencies]
dev = [
    "jupyter>=1,<2",
    "notebook>=7.0.7,<8",
    "pycodestyle>=2,<3",
    "autopep8>=2,<3",
    "matplotlib>=3,<4",
    "rope>=1,<2",
    "pytest-watch>=4.2.0,<5",
]

[tool.uv.sources]
wps-shared = { workspace = true }
wps-sfms = { workspace = true }
wps-wf1 = { workspace = true }
cffdrs = { git = "https://github.com/cffdrs/cffdrs_py.git", rev = "c760307" }

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/app"]
