[project]
name = "wps-shared"
version = "0.1.0"
description = "Wildfire Predictive Services Unit Shared Library"
authors = [
    {name = "Darren Boss", email = "darren.boss@gov.bc.ca"}
]
readme = "README.md"
requires-python = ">=3.12.3,<4.0"
dependencies = [
    "sqlalchemy>=2,<3",
    "aiohttp>=3,<4",
    "requests>=2,<3",
    "python-decouple>=3,<4",
    "geopandas>=1.0.1,<2",
    "shapely>=2.0.5,<3",
    "pydantic>=2.10.6,<3",
    "aiobotocore>=2.0.0,<3",
    "geoalchemy2>=0,<1",
    "affine>=2.4.0,<3",
    "fastapi>=0.115.11,<1",
    "sentry-sdk>=2.22.0,<3",
    "pyjwt>=2.10.1,<3",
    "psycopg2-binary>=2.9.10,<3",
    "asyncpg>=0.30.0,<1",
    "redis>=7.0.0,<8",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.0,<10",
    "pytest-mock>=3,<4",
    "coverage>=7.6.4,<8",
    "ruff>=0.11.5,<1",
    "testcontainers[postgres]>=4.10.0,<5",
    "pytest-cov>=7.0.0,<8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/wps_shared"]
